### ISSUE TITLE
Please change issue link

### ISSUE THREAD

**Issue by pcav** [liaduarte/QGIS-applications#1]
It currently point to the repo page, not to the /issues/ one.
Thanks.

**Comment by liaduarte** [comment]
Sorry Ii didn't understand what you mean. Please clarify to me.
thanks

**Comment by pcav** [comment]
currently from:
http://plugins.qgis.org/plugins/DRASTIC/
one is directed to:
https://github.com/liaduarte/QGIS-applications.git
instead of:
https://github.com/liaduarte/QGIS-applications/issues/

**Comment by liaduarte** [comment]
Done.
Thank you.
